x-wharfmap:
  backgroundColor: "#f5f5f583"
  backgroundBorderColor: "#cccccc"
  backgroundBorderWidth: 2
  networks:
    etl-network:
      color: "#acbde5"          # Light yellow for ETL network
      border-color: "#8bb4df"
      border-width: "2px"
      border-style: "solid"
  conditions:
    service_healthy:
      stroke-width: "1px"
      stroke-dasharray: "0 0"


services:
  extract:
    build: ETL/extract
    container_name: extract-service
    restart: unless-stopped
    volumes:
      - ./ETL/extract:/app
      - taxi_raw_data:/data/raw      
    command: ["python", "main.py"]
    env_file: .env
    depends_on:
      rabbitMQ:
        condition: service_healthy     
    networks:
      - etl-network
    x-wharfmap:
      color: "#D82C20"
      border-color: "#7A0C00"
      border-width: "3px"      
      border-style: "solid"

  
  transform:
    build: ETL/transform
    container_name: transform-service
    restart: unless-stopped
    mem_limit: 6g
    volumes:
      - ./ETL/transform:/app
      - taxi_raw_data:/data/raw      
      - taxi_processed_data:/data/processed
    command: ["python", "main.py"]
    env_file: .env
    depends_on:
      rabbitMQ:
        condition: service_healthy     
    networks:
      - etl-network
    x-wharfmap:
      color: "#d89120"
      border-color: "#aa731b"
      border-width: "3px"      
      border-style: "solid"

  rabbitMQ:
    image: rabbitmq:3-management
    container_name: rabbitmq-service
    restart: unless-stopped
    env_file: .env
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - etl-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 15s
      timeout: 10s
      retries: 5
    x-wharfmap:
      color: "#20a1d8"
      border-color: "#1b33aa"
      border-width: "1px"      
      border-style: "dashed"

volumes:
  rabbitmq_data:
  taxi_raw_data:
  taxi_processed_data:

networks:
  etl-network:
    driver: bridge